version: '2.1'
services:
  web:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '3000:3000'
    command:
      - yarn
      - start
