export const APPEND_NEW_TEAM='APPEND_NEW_TEAM';
export const UPDATE_TEAM_LIST='UPDATE_TEAM_LIST';
export const UPDATE_SELECTED_TEAM='UPDATE_SELECTED_TEAM';
export const FETCH_USER_TEAMS='FETCH_USER_TEAMS';
